<a href="https://colab.research.google.com/github/ortutayzoltan/PyTorchBasics/blob/main/PyTorchBasics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PyTorch Basics: A Quick Start Guide

## Setup and Installation
First, import the necessary libraries:

In [ ]:
import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np

## Tensors: The Building Blocks
Tensors are the fundamental data structure in PyTorch, similar to NumPy arrays but with GPU support.

In [ ]:
# Creating tensors
x = torch.tensor([1, 2, 3])
print(f"1D tensor: {x}")

# Create a 2D tensor (matrix)
matrix = torch.tensor([[1, 2], [3, 4]])
print(f"2D tensor:\n{matrix}")

# Create tensors with specific data types
float_tensor = torch.tensor([1.0, 2.0, 3.0], dtype=torch.float32)
print(f"Float tensor: {float_tensor}")

# Create tensors with specific shapes
zeros = torch.zeros(2, 3)  # 2x3 tensor of zeros
ones = torch.ones(2, 3)    # 2x3 tensor of ones
print(f"Zeros:\n{zeros}")
print(f"Ones:\n{ones}")

1D tensor: tensor([1, 2, 3])
2D tensor:
tensor([[1, 2],
        [3, 4]])
Float tensor: tensor([1., 2., 3.])
Zeros:
tensor([[0., 0., 0.],
        [0., 0., 0.]])
Ones:
tensor([[1., 1., 1.],
        [1., 1., 1.]])


## Basic Operations


In [ ]:
# Arithmetic operations
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])

print(f"Addition: {a + b}")
print(f"Multiplication: {a * b}")  # Element-wise multiplication
print(f"Matrix multiplication: {torch.matmul(a, b)}")  # Dot product

# Reshaping tensors
c = torch.tensor([1, 2, 3, 4, 5, 6])
reshaped = c.reshape(2, 3)
print(f"Reshaped tensor:\n{reshaped}")

# Indexing and slicing
print(f"First row: {reshaped[0]}")
print(f"First column: {reshaped[:, 0]}")

Addition: tensor([5, 7, 9])
Multiplication: tensor([ 4, 10, 18])
Matrix multiplication: 32
Reshaped tensor:
tensor([[1, 2, 3],
        [4, 5, 6]])
First row: tensor([1, 2, 3])
First column: tensor([1, 4])


## Neural Network Basics
Here's a simple neural network example:

In [ ]:
# Define a simple neural network
class SimpleNN(nn.Module):
    def __init__(self):
        super(SimpleNN, self).__init__()
        self.linear1 = nn.Linear(2, 4)  # 2 inputs, 4 hidden units
        self.relu = nn.ReLU()
        self.linear2 = nn.Linear(4, 1)  # 4 hidden units, 1 output

    def forward(self, x):
        x = self.linear1(x)
        x = self.relu(x)
        x = self.linear2(x)
        return x

# Create model instance
model = SimpleNN()
print(f"Model structure:\n{model}")

Model structure:
SimpleNN(
  (linear1): Linear(in_features=2, out_features=4, bias=True)
  (relu): ReLU()
  (linear2): Linear(in_features=4, out_features=1, bias=True)
)


## Training Loop Example
Here's a basic training loop:

In [ ]:
# Generate some dummy data
X = torch.randn(100, 2)  # 100 samples, 2 features
y = torch.sin(X[:, 0]) + torch.cos(X[:, 1]).reshape(-1, 1)  # Target values

# Initialize model and optimizer
model = SimpleNN()
criterion = nn.MSELoss()
optimizer = optim.SGD(model.parameters(), lr=0.01)

# Training loop
for epoch in range(100):
    # Forward pass
    outputs = model(X)
    loss = criterion(outputs, y)

    # Backward pass and optimization
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    if (epoch + 1) % 10 == 0:
        print(f'Epoch [{epoch+1}/100], Loss: {loss.item():.4f}')

Epoch [10/100], Loss: 0.8850
Epoch [20/100], Loss: 0.7794
Epoch [30/100], Loss: 0.7254
Epoch [40/100], Loss: 0.6958
Epoch [50/100], Loss: 0.6781
Epoch [60/100], Loss: 0.6665
Epoch [70/100], Loss: 0.6583
Epoch [80/100], Loss: 0.6519
Epoch [90/100], Loss: 0.6468
Epoch [100/100], Loss: 0.6425


/usr/local/lib/python3.11/dist-packages/torch/nn/modules/loss.py:608: UserWarning: Using a target size (torch.Size([100, 100])) that is different to the input size (torch.Size([100, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)


## GPU Support
PyTorch makes it easy to use GPU acceleration:

In [ ]:
# Check if GPU is available
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

# Move tensor to GPU
if torch.cuda.is_available():
    x = x.to(device)
    model = model.to(device)

Using device: cpu


## Saving and Loading Models
PyTorch provides easy ways to save and load models:

In [ ]:
# Save model
torch.save(model.state_dict(), 'model.pth')

# Load model
model = SimpleNN()
model.load_state_dict(torch.load('model.pth'))
model.eval()  # Set the model to evaluation mode

<ipython-input-10-60301716931b>:6: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load('model.pth'))


SimpleNN(
  (linear1): Linear(in_features=2, out_features=4, bias=True)
  (relu): ReLU()
  (linear2): Linear(in_features=4, out_features=1, bias=True)
)

## Common Neural Network Layers
Here are some commonly used layers in PyTorch:

In [ ]:
# Common layer types
conv = nn.Conv2d(in_channels=3, out_channels=16, kernel_size=3)  # Convolutional layer
pool = nn.MaxPool2d(kernel_size=2)  # Max pooling layer
dropout = nn.Dropout(p=0.5)  # Dropout layer
batch_norm = nn.BatchNorm2d(16)  # Batch normalization